"""Geographic utilities for country coordinates and mapping."""

COUNTRY_COORDS: dict[str, dict[str, float]] = {
    "US": {"lat": 39.83, "lng": -98.58},
    "GB": {"lat": 55.38, "lng": -3.44},
    "UK": {"lat": 55.38, "lng": -3.44},
    "DE": {"lat": 51.17, "lng": 10.45},
    "FR": {"lat": 46.23, "lng": 2.21},
    "SG": {"lat": 1.35, "lng": 103.82},
    "AU": {"lat": -25.27, "lng": 133.78},
    "JP": {"lat": 36.20, "lng": 138.25},
    "AE": {"lat": 23.42, "lng": 53.85},
    "UAE": {"lat": 23.42, "lng": 53.85},
    "IN": {"lat": 20.59, "lng": 78.96},
    "CN": {"lat": 35.86, "lng": 104.20},
    "HK": {"lat": 22.40, "lng": 114.11},
    "CH": {"lat": 46.82, "lng": 8.23},
    "BR": {"lat": -14.24, "lng": -51.93},
    "CA": {"lat": 56.13, "lng": -106.35},
    "MX": {"lat": 23.63, "lng": -102.55},
    "ZA": {"lat": -30.56, "lng": 22.94},
    "NG": {"lat": 9.08, "lng": 8.68},
    "KE": {"lat": -0.02, "lng": 37.91},
    "SA": {"lat": 23.89, "lng": 45.08},
    "KR": {"lat": 35.91, "lng": 127.77},
    "NL": {"lat": 52.13, "lng": 5.29},
    "SE": {"lat": 60.13, "lng": 18.64},
    "IT": {"lat": 41.87, "lng": 12.57},
    "ES": {"lat": 40.46, "lng": -3.75},
    "PH": {"lat": 12.88, "lng": 121.77},
    "MY": {"lat": 4.21, "lng": 101.98},
    "TH": {"lat": 15.87, "lng": 100.99},
    "ID": {"lat": -0.79, "lng": 113.92},
    "PL": {"lat": 51.92, "lng": 19.15},
    "RU": {"lat": 61.52, "lng": 105.32},
    "TR": {"lat": 38.96, "lng": 35.24},
    "EG": {"lat": 26.82, "lng": 30.80},
    "CL": {"lat": -35.68, "lng": -71.54},
    "CO": {"lat": 4.57, "lng": -74.30},
    "PE": {"lat": -9.19, "lng": -75.02},
    "AR": {"lat": -38.42, "lng": -63.62},
    "NZ": {"lat": -40.90, "lng": 174.89},
    "IE": {"lat": 53.14, "lng": -7.69},
    "LU": {"lat": 49.82, "lng": 6.13},
    "BE": {"lat": 50.50, "lng": 4.47},
    "AT": {"lat": 47.52, "lng": 14.55},
    "FI": {"lat": 61.92, "lng": 25.75},
    "DK": {"lat": 56.26, "lng": 9.50},
    "NO": {"lat": 60.47, "lng": 8.47},
    "PT": {"lat": 39.40, "lng": -8.22},
    "IL": {"lat": 31.05, "lng": 34.85},
    "TW": {"lat": 23.70, "lng": 120.96},
}

COUNTRY_NAMES: dict[str, str] = {
    "US": "United States",
    "GB": "United Kingdom",
    "UK": "United Kingdom",
    "DE": "Germany",
    "FR": "France",
    "SG": "Singapore",
    "AU": "Australia",
    "JP": "Japan",
    "AE": "United Arab Emirates",
    "UAE": "United Arab Emirates",
    "IN": "India",
    "CN": "China",
    "HK": "Hong Kong",
    "CH": "Switzerland",
    "BR": "Brazil",
    "CA": "Canada",
    "MX": "Mexico",
    "ZA": "South Africa",
    "NG": "Nigeria",
    "KE": "Kenya",
    "SA": "Saudi Arabia",
    "KR": "South Korea",
    "NL": "Netherlands",
    "SE": "Sweden",
    "IT": "Italy",
    "ES": "Spain",
    "PH": "Philippines",
    "MY": "Malaysia",
    "TH": "Thailand",
    "ID": "Indonesia",
    "PL": "Poland",
    "RU": "Russia",
    "TR": "Turkey",
    "EG": "Egypt",
    "CL": "Chile",
    "CO": "Colombia",
    "PE": "Peru",
    "AR": "Argentina",
    "NZ": "New Zealand",
    "IE": "Ireland",
    "LU": "Luxembourg",
    "BE": "Belgium",
    "AT": "Austria",
    "FI": "Finland",
    "DK": "Denmark",
    "NO": "Norway",
    "PT": "Portugal",
    "IL": "Israel",
    "TW": "Taiwan",
}

CURRENCY_MAP: dict[str, str] = {
    "US": "USD",
    "GB": "GBP",
    "UK": "GBP",
    "DE": "EUR",
    "FR": "EUR",
    "SG": "SGD",
    "AU": "AUD",
    "JP": "JPY",
    "AE": "AED",
    "UAE": "AED",
    "IN": "INR",
    "CN": "CNY",
    "HK": "HKD",
    "CH": "CHF",
    "BR": "BRL",
    "CA": "CAD",
    "MX": "MXN",
    "ZA": "ZAR",
    "NG": "NGN",
    "KE": "KES",
    "SA": "SAR",
    "KR": "KRW",
    "NL": "EUR",
    "SE": "SEK",
    "IT": "EUR",
    "ES": "EUR",
    "PH": "PHP",
    "MY": "MYR",
    "TH": "THB",
    "ID": "IDR",
    "PL": "PLN",
    "RU": "RUB",
    "TR": "TRY",
    "EG": "EGP",
    "CL": "CLP",
    "CO": "COP",
    "PE": "PEN",
    "AR": "ARS",
    "NZ": "NZD",
    "IE": "EUR",
    "LU": "EUR",
    "BE": "EUR",
    "AT": "EUR",
    "FI": "EUR",
    "DK": "DKK",
    "NO": "NOK",
    "PT": "EUR",
    "IL": "ILS",
    "TW": "TWD",
}


def get_coords(country_code: str) -> dict[str, float]:
    return COUNTRY_COORDS.get(country_code, {"lat": 0.0, "lng": 0.0})


def get_currency(country_code: str) -> str:
    return CURRENCY_MAP.get(country_code, "USD")


def get_country_name(country_code: str) -> str:
    return COUNTRY_NAMES.get(country_code, country_code)
