from enum import Enum


class PaymentStage(str, Enum):
    INITIATED = "INITIATED"
    VALIDATION = "VALIDATION"
    COMPLIANCE = "COMPLIANCE"
    FX = "FX"
    ROUTING = "ROUTING"
    SETTLEMENT = "SETTLEMENT"
    RECONCILIATION = "RECONCILIATION"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ON_HOLD = "ON_HOLD"


STAGE_ORDER = [
    PaymentStage.INITIATED,
    PaymentStage.VALIDATION,
    PaymentStage.COMPLIANCE,
    PaymentStage.FX,
    PaymentStage.ROUTING,
    PaymentStage.SETTLEMENT,
    PaymentStage.RECONCILIATION,
    PaymentStage.COMPLETED,
]


class PaymentStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ON_HOLD = "ON_HOLD"
    DELAYED = "DELAYED"


class PaymentPriority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class PaymentType(str, Enum):
    SWIFT = "SWIFT"
    WIRE = "WIRE"
    ACH = "ACH"
    SEPA = "SEPA"
    RTGS = "RTGS"
    INSTANT = "INSTANT"


class AnomalyType(str, Enum):
    SANCTIONS_FALSE_POSITIVE = "SANCTIONS_FALSE_POSITIVE"
    GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    FX_DELAY = "FX_DELAY"
    MISSING_INTERMEDIARY = "MISSING_INTERMEDIARY"
    SETTLEMENT_DELAY = "SETTLEMENT_DELAY"
    RECONCILIATION_MISMATCH = "RECONCILIATION_MISMATCH"


class AnomalySeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AnomalyScope(str, Enum):
    PAYMENT = "PAYMENT"
    SYSTEM = "SYSTEM"
    CORRIDOR = "CORRIDOR"
    COUNTRY = "COUNTRY"


class AnomalyStatus(str, Enum):
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    RESOLVED = "RESOLVED"


class ActionStatus(str, Enum):
    OPEN = "OPEN"
    TRIAGED = "TRIAGED"
    IN_PROGRESS = "IN_PROGRESS"
    MITIGATED = "MITIGATED"
    RESOLVED = "RESOLVED"


class EventType(str, Enum):
    STAGE_TRANSITION = "STAGE_TRANSITION"
    ANOMALY_DETECTED = "ANOMALY_DETECTED"
    COMPLIANCE_CHECK = "COMPLIANCE_CHECK"
    FX_QUOTE = "FX_QUOTE"
    ROUTE_SELECTED = "ROUTE_SELECTED"
    SETTLEMENT_INITIATED = "SETTLEMENT_INITIATED"
    RECONCILIATION_CHECK = "RECONCILIATION_CHECK"
    HOLD_APPLIED = "HOLD_APPLIED"
    RETRY_ATTEMPTED = "RETRY_ATTEMPTED"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    ESCALATION = "ESCALATION"
    OPERATOR_INTERVENTION = "OPERATOR_INTERVENTION"
    SLA_BREACH = "SLA_BREACH"
    ROUTE_FAILOVER = "ROUTE_FAILOVER"


class LogLevel(str, Enum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class NodeType(str, Enum):
    CORRESPONDENT_BANK = "CORRESPONDENT_BANK"
    GATEWAY = "GATEWAY"
    COMPLIANCE_HUB = "COMPLIANCE_HUB"
    SETTLEMENT_NETWORK = "SETTLEMENT_NETWORK"
    FX_PROVIDER = "FX_PROVIDER"
    CLEARING_HOUSE = "CLEARING_HOUSE"


class RouteType(str, Enum):
    DIRECT = "DIRECT"
    INTERMEDIARY = "INTERMEDIARY"
    MULTI_HOP = "MULTI_HOP"


class NodeHealthStatus(str, Enum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    CRITICAL = "CRITICAL"
    OFFLINE = "OFFLINE"
